//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MobyClient.Resources.Strings {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MobyClient.Resources.Strings.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There does not seem to be any connection to the Internet.  Check your connectivity and retry..
        /// </summary>
        internal static string ErrorConnectivityMsg {
            get {
                return ResourceManager.GetString("ErrorConnectivityMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connectivity.
        /// </summary>
        internal static string ErrorConnectivityTitle {
            get {
                return ResourceManager.GetString("ErrorConnectivityTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid password.
        /// </summary>
        internal static string ErrorLoginInvalidPasswordTitle {
            get {
                return ResourceManager.GetString("ErrorLoginInvalidPasswordTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid username.
        /// </summary>
        internal static string ErrorLoginInvalidUsernameTitle {
            get {
                return ResourceManager.GetString("ErrorLoginInvalidUsernameTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password not found or cannot be blank.
        /// </summary>
        internal static string ErrorLogInMissingPasswordMsg {
            get {
                return ResourceManager.GetString("ErrorLogInMissingPasswordMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username not found or cannot be blank.
        /// </summary>
        internal static string ErrorLogInMissingUsernameMsg {
            get {
                return ResourceManager.GetString("ErrorLogInMissingUsernameMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Username/Password used does not match any profiles on record. Please try again..
        /// </summary>
        internal static string ErrorLogInUsernamePasswordNotFoundMsg {
            get {
                return ResourceManager.GetString("ErrorLogInUsernamePasswordNotFoundMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username or password not found.
        /// </summary>
        internal static string ErrorLogInUsernamePasswordNotFoundTitle {
            get {
                return ResourceManager.GetString("ErrorLogInUsernamePasswordNotFoundTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Logistics Service was found running.  Check to see that the Moby Logistics Service is installed correctly and running and then retry..
        /// </summary>
        internal static string ErrorNoLogisticsServiceMsg {
            get {
                return ResourceManager.GetString("ErrorNoLogisticsServiceMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Logistics Service running.
        /// </summary>
        internal static string ErrorNoLogisticsServiceTitle {
            get {
                return ResourceManager.GetString("ErrorNoLogisticsServiceTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log In.
        /// </summary>
        internal static string LabelLogin {
            get {
                return ResourceManager.GetString("LabelLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Moby Login.
        /// </summary>
        internal static string LabelMobyLogin {
            get {
                return ResourceManager.GetString("LabelMobyLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password:.
        /// </summary>
        internal static string LabelPassword {
            get {
                return ResourceManager.GetString("LabelPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username:.
        /// </summary>
        internal static string LabelUsername {
            get {
                return ResourceManager.GetString("LabelUsername", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string LoginOK {
            get {
                return ResourceManager.GetString("LoginOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calendar.
        /// </summary>
        internal static string PageCalendar {
            get {
                return ResourceManager.GetString("PageCalendar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contacts.
        /// </summary>
        internal static string PageContacts {
            get {
                return ResourceManager.GetString("PageContacts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dashboard.
        /// </summary>
        internal static string PageDashboard {
            get {
                return ResourceManager.GetString("PageDashboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        internal static string PageEmails {
            get {
                return ResourceManager.GetString("PageEmails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Messages.
        /// </summary>
        internal static string PageMessages {
            get {
                return ResourceManager.GetString("PageMessages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        internal static string PageSettings {
            get {
                return ResourceManager.GetString("PageSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shared Content.
        /// </summary>
        internal static string PageSharedContent {
            get {
                return ResourceManager.GetString("PageSharedContent", resourceCulture);
            }
        }
    }
}
