//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MobyClient.Schemas;

// 
// This source code was auto-generated by xsd, Version=4.8.3928.0.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
[System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
public partial class MobyModules {
    
    private MobyModule[] itemsField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("MobyModule", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public MobyModule[] Items {
        get {
            return this.itemsField;
        }
        set {
            this.itemsField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class MobyModule {
    
    private string fontFamilyField;
    
    private string fontIconNameField;
    
    private string fontSizeField;
    
    private string isShownField;
    
    private string moduleMenuLocationField;
    
    private string moduleNameField;
    
    private string moduleDescriptionField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string FontFamily {
        get {
            return this.fontFamilyField;
        }
        set {
            this.fontFamilyField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string FontIconName {
        get {
            return this.fontIconNameField;
        }
        set {
            this.fontIconNameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string FontSize {
        get {
            return this.fontSizeField;
        }
        set {
            this.fontSizeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string IsShown {
        get {
            return this.isShownField;
        }
        set {
            this.isShownField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string ModuleMenuLocation {
        get {
            return this.moduleMenuLocationField;
        }
        set {
            this.moduleMenuLocationField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string ModuleName {
        get {
            return this.moduleNameField;
        }
        set {
            this.moduleNameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string ModuleDescription {
        get {
            return this.moduleDescriptionField;
        }
        set {
            this.moduleDescriptionField = value;
        }
    }
}
